language: r
cache: packages
sudo: false

# r_packages:
#  - sem
#  - qgraph
#  - semPlot

os: 
- linux
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-7
    - g++-7
    - gfortran-7
# - osx

r:
  - release
    #  - devel 

install:
- mkdir -p ~/.R
- ./util/travis/install-$TRAVIS_OS_NAME

script: "./util/travis/script"

warnings_are_errors: true    
r_check_args: "--run-dontrun"

# before_install:
#   Rscript -e 'update.packages(ask = FALSE)'