language: r
cache: packages
sudo: false

# r_packages:
#  - sem
#  - qgraph
#  - semPlot

os: 
- linux
- osx

r:
  - release
    #  - devel 

warnings_are_errors: true    
r_check_args: "--run-dontrun"

before_install:
  Rscript -e 'update.packages(ask = FALSE)'        
